### ISSUE TITLE
ImportError: cannot import name '_power_of_two' from 'enum'

### ISSUE THREAD

**Issue by zevaryx** [domdfcoding/enum_tools#39]
## Description

Adding `enum_tools.autoenum` to Sphinx on Python 3.10 causes the following error:

`ImportError: cannot import name '_power_of_two' from 'enum'`

## Steps to Reproduce

   1. Install Python 3.10
   2. Run `make html` with `enum_tools.autoenum` installed

## Actual result:

`ImportError: cannot import name '_power_of_two' from 'enum'`

## Expected result:
Better enum autodocs

## Reproduces how often:

Easily reproduced

## Version

  * Operating System: Windows 11 22471.1000
  * Python: 3.10.0
  * enum_tools: 0.6.4

## Installation source

PyPi

## Other Additional Information:

A solution would be to replace [enum_tools/custom_enums.py#L50](https://github.com/domdfcoding/enum_tools/blob/master/enum_tools/custom_enums.py#L50) with the [Python main branch implementation](https://github.com/python/cpython/blob/main/Lib/enum.py#L1387)

**Comment by domdfcoding** [comment]
Hi @zevaryx, sorry about that. The CPython developers decided postpone the changes to the `enum` module until 3.11 which is what broke the import.

It should be sorted in [version 0.6.5](https://pypi.org/project/enum-tools/0.6.5/). Can you try that version, and if it works for you I'll close the issue.

**Comment by bahlo** [comment]
I'm having the same issue with Python 3.12.4 and enum_tools@0.9.0-post1

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  OMITTED
  File "/Users/arne/Developer/bahlo/xxx/.venv/lib/python3.12/site-packages/enum_tools/__init__.py", line 30, in <module>
    from enum_tools.custom_enums import AutoNumberEnum, DuplicateFreeEnum, IntEnum, OrderedEnum, StrEnum
  File "/Users/arne/Developer/bahlo/xxx.venv/lib/python3.12/site-packages/enum_tools/custom_enums.py", line 50, in <module>
    from enum import _power_of_two
ImportError: cannot import name '_power_of_two' from 'enum' (/Users/arne/.local/share/mise/installs/python/3.12.4/lib/python3.12/enum.py)
```

How can I fix this?

**Comment by domdfcoding** [comment]
Can you upgrade to the latest enum-tools (0.12.0), or is there a conflict
with another dependency? 0.10.0 and 0.11.0 also have the fix for this
issue.
