### ISSUE TITLE
After update - cannot import name 'RequestsURL' from 'apeye.url'

### ISSUE THREAD

**Issue by 1kastner** [domdfcoding/enum_tools#54]
## Description

I had a working setup, and then I was re-recreating the whole virtual environment for an unrelated reason. Out of the sudden the following error popped up:

```
PS XXX\docs> .\make.bat html
Running Sphinx v4.4.0
Extension error:
Could not import extension enum_tools.autoenum (exception: cannot import name 'RequestsURL' from 'apeye.url' (VENV_DIR\lib\site-packages\apeye\url.py))
```

This error message creates the imporession that enum_tools is the culprit here which I believe in fact it isn't.

## Steps to Reproduce

A simple import suffices.
```
PS XXX> python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apeye
>>> print(apeye.__version__)
1.1.0
>>> import enum_tools
>>> print(enum_tools.__version__)
0.8.0
>>> from enum_tools import autoenum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "VENV_DIR\lib\site-packages\enum_tools\autoenum.py", line 77, in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation  # nodep
  File "VENV_DIR\lib\site-packages\sphinx_toolbox\__init__.py", line 36, in <module>
    from sphinx_toolbox import (
  File "VENV_DIR\lib\site-packages\sphinx_toolbox\assets.py", line 111, in <module>
    from sphinx_toolbox.utils import SphinxExtMetadata
  File "VENV_DIR\lib\site-packages\sphinx_toolbox\utils.py", line 40, in <module>
    from apeye.url import RequestsURL
ImportError: cannot import name 'RequestsURL' from 'apeye.url' (VENV_DIR\lib\site-packages\apeye\url.py)
>>>
```

The traceback indicates that the sphinx toolbox uses an outdated version of apeye and thus this error appears. Maybe the error message in the initial output could be even clearer to better guide the user?

## Installation source
I installed everything via pip

**Comment by 1kastner** [comment]
After the sphinx-toolbox release and qn update on my side this was resolved.
